# Generated by Django 3.1 on 2020-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='usr', max_length=30),
            preserve_default=False,
        ),
    ]
