# Generated by Django 3.1 on 2020-08-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
